
services:
  - type: web
    name: chatbot-jzf
    env: node
    plan: free
    buildCommand: bash render-build.sh
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.12.0
      - key: NODE_OPTIONS
        value: --max-old-space-size=400
      - key: API_KEY
        sync: false
